# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181014_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
